db.url=jdbc:postgresql://localhost:5432/badminton_club
db.username=postgres
db.password=Altynay0824
db.driver=org.postgresql.Driver
db.poolSize=10

spring.messages.basename=messages
spring.messages.encoding=UTF-8

logging.level.root=INFO
logging.level.com.badmintonclub=DEBUG